### ISSUE TITLE
We own the `scarlettrobotics.com` domain don't we? Who owns that?

### ISSUE THREAD

**Issue by Quantum158** [ScarlettRobotics/ScarlettRobotics.github.io#1]
If we can track down the owner we should try and take over that.

Probably better than the free `.ml` (region of Mali) domain which is currently used...

**Comment by kevinlul** [comment]
Maybe years in the past, but it seems like it stopped being paid for. I recall during my term the CBE instituted a policy that required clubs to be under a CBE domain rather than going off on their own.

![image](https://user-images.githubusercontent.com/6320810/142498785-3bfb9c7d-3fec-45eb-9a63-0196bba5a359.png)

**Comment by Quantum158** [comment]
Ah darn

> I recall during my term the CBE instituted a policy that required clubs to be under a CBE domain rather than going off on their own.

That's super important anyway, @Kappabyte make sure you check that!

**Comment by Kappabyte** [comment]
Are you sure that policy exists? The scarlett music program owns and uses the domain epscarlettmusic.com, which is not only used for information but also to collect fees (independently from the school). If either of you have a copy of this policy, if could attach it here, or send it to me on slack, that would be great.

**Comment by Quantum158** [comment]
That is a question for the mentors and the school board itself

**Comment by Kappabyte** [comment]
I will bring this up next meeting. I am going to close the issue for now.

**Comment by kevinlul** [comment]
> Are you sure that policy exists? The scarlett music program owns and uses the domain epscarlettmusic.com, which is not only used for information but also to collect fees (independently from the school). If either of you have a copy of this policy, if could attach it here, or send it to me on slack, that would be great.

This is something I was told back then. Keep in mind that I was last in high school almost five years ago, so that's more than enough time for policies to change again through that many cycles of students in and graduating.

**Comment by Kappabyte** [comment]
The domain [https://scarlettrobotics.com](https://scarlettrobotics.com) has been reacquired, and has been pointed to the site.

As for CBE policy, I asked my father who is the principle at another school, and he is aware of no such policy. We will continue to operate the site unless we are told we cannot.
